site_name: AMANEQ User Guide
site_description: AMANEQ User Guide
site_author: Ryotaro Honda
copyright: KEK IPNS
repo_url: https://github.com/spadi-alliance/ug-amaneq
repo_name: ug-amaneq

theme:
  name: material
  features:
    - toc.integrate
    - navigation.tabs
  palette:
    #    scheme: slate
    scheme: default
    primary: pink

markdown_extensions:
  - attr_list
  - def_list
  - markdown_katex:
      no_inline_svg: true
      insert_fonts_css: true
  #  - hbfm.inline_coloring
  #  - hbfm.inline_list
  #  - toc:
  #      slugify: !!python/name:hbfm.toc.slugify
  #- hbfm.number_headers
  #- hbfm.quote_uri_hash
  - image_captions:
      numbering: true
  - caption:
      numbering: true

extra_css:
  - css/custom.css

nav:
  - Top: index.md
  - Release: release/release.md
  - Hardware:
      - Overview: hardware/overview/overview.md
      - Mezzanine cards: hardware/mezzanine/mezzanine.md
      - Housing: hardware/housing/housing.md
      - Differences in HUL: hardware/diff-hul/diff-hul.md
      - For developers: hardware/for-developers/for-developers.md
  - Synchronization: synchronization/sync.md
  - Firmware:
      - Overview: firmware/overview/overview.md
      - Skeleton: firmware/skeleton/skeleton.md
      - Str-LRTDC: firmware/strlrtdc/strlrtdc.md
      - Str-LRTDC-10G: firmware/strlrtdc-10g/strlrtdc-10g.md
      - Str-HRTDC: firmware/strhrtdc/strhrtdc.md
      - MikuCLockRoot: firmware/clockroot/clockroot.md
      - MikuCLockHub: firmware/clockhub/clockhub.md
  - Software: software/software.md
  - Practical Usage: practical/practical.md
